### ISSUE TITLE
Searching "sinaloa cartel" (without quotes)  yields zero results; "foreign affairs" yields incorrect result set

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/obento#315]
This doesn't seem right.

**Comment by kerchner** [comment]
This appears to be an issue with encoding of the query parameter at the presentation layer (PHP vs. home.html).  Here is what we know so far:

Results below are for **index.php**

query:  sinaloa cartel

browser | m9_001 | m9_002
---|---|---
Firefox | 385 | 0 (385 via articles_html))
Chrome | 0 (but 385 via articles_html) | 0 (385 via articles_html)


query:  foreign affairs

browser | m9_001 | m9_002
---|---|---
Firefox | 259K | 70K (259K via articles_html)
Chrome | 0 (70K via home.html, 259K via /everything or via /articles_html) |  70K (259K via articles_html)

**Comment by MustafaDasorwala** [comment]
Below is the summary of what I think need to be changed as per my analysis till now. 

Issue 1:
our initial query
query = u'+id:db-* +(name:%s OR description:%s)' % (q, q)

this format works well in case of single term query, but in case where the query has multiple terms like "foreign affairs" it is not evaluated as we expected it to.
We assumed that the query will be evaluated as
+id:db-* +(name:foreign AND Affairs OR description:foreign AND affairs) since we have specified the defualtOperator = "AND" in schema.xml. But as per solr documentation we shouldn't reply on the defaultOperator parameter as it is not consistently use and will be deprecated in the future. So the query was actually being evaluated as +id:db-* +(name:foreign OR Affairs OR description:foreign OR affairs) and therefore we were getting too many results for the query.
The other misunderstanding that we had was we  assumed that all the terms will be searched under name when specified after 'name:' which is not true the system actually reads the query as +id:db-* +(name:foreign OR text:affairs OR description:foreign OR text:affairs) where 'text' is the default field. The temporary solution that we implemented inserted '+' between different terms the plus sign acted like AND operator giving us the desired results 

Valid queries:
+id:db* +(name:(foreign AND affairs) OR description:(foreign AND affairs))
+id:db* AND foreign AND affairs // this works for us since we are not specifying any boosting values
+id:db* +(name:(+foreign +affairs) OR description:(+foreign +affairs))
+id:db* +((name:foreign AND name:affairs) OR (description:foreign AND description:affairs))
etc.

Phrase Query 
+id:db* +(name:("foreign affairs") OR description:("foreign affairs"))
+id:db* AND "foreign affairs"
etc

Note: It was decided to use the 1st query format

Issue 2:
No stemming filter is being applied to name field this restricts the return results in order to correct this we need to change the field type of name field to "text" instead of "textgen" in schema.xml

Issue 3:
Currently terms like C++, C#, .NET are not being indexed/queried properly. We need to create and specify custom filters to address this issue.

**Comment by MustafaDasorwala** [comment]
Issue 3 will be addressed  in seperate ticket.

**Comment by kerchner** [comment]
Since name, description, issn, etc. are all being copied into text (as spec'd in the solr schema) we can simplify the queries in views.py to just search on ```text:```.

@MustafaDasorwala and I noted that the solr console and the code are giving different result sets.  As an example, foreign affairs yields 1 result through the solr console, but multiple results through the code.  Is this due to how we're passing the query to solrpy, or something in solrpy itself?

**Comment by kerchner** [comment]
Ideally what we want is results for a multi-word query of "A B C" where each result contains A, B, and C, even if they're not contiguous.   Solr (via the code) is at least ranking the results with all terms highest, but is still including results where not all terms are present.

First thing to do is understand why these aren't consistent.

**Comment by kerchner** [comment]
It may be worth trying a different library in place of solrpy?

**Comment by kerchner** [comment]
Also see if there is a solr log that might show the queries being passed from the app via solrpy
